In [36]:
import numpy as np

In [37]:
first_array = np.array([[10,20,30],[40,50,60]])

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (2,3)

In [70]:
print(first_array)

[[10  0 30]
 [40 50 60]]


In [39]:
for i in first_array:
    print(i)

[10 20 30]
[40 50 60]


In [40]:
for i in first_array:
    for j in i: 
        print(j)

10
20
30
40
50
60


In [41]:
type(first_array)

numpy.ndarray

In [42]:
second_array = np.array(range(100))

In [43]:
print(second_array.reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [54]:
third_array = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [55]:
for i in third_array:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


In [56]:
for i in np.nditer(third_array):
    print(i)

0
1
2
3
4
5
6
7


In [57]:
# hey, binary to decimal system, I'm lucky :)
for i,j in np.ndenumerate(third_array):
    print(i,j)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7
