In [2]:
import torch

In [4]:
import numpy as np

In [6]:
torch.__version__

'2.2.1+cpu'

In [8]:
arr = np.array([1,2,3,4,5])

In [9]:
arr

array([1, 2, 3, 4, 5])

In [12]:
arr.dtype

dtype('int32')

In [13]:
type(arr)

numpy.ndarray

In [15]:
# indicate tensor in pytorch method 1
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [17]:
# indicate tensor in pytorch method 2
x = torch.as_tensor(arr)

In [19]:
x.dtype

torch.int32

In [36]:
arr2d = np.arange(0.0,12.0)

In [37]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [38]:
arr2d = arr2d.reshape(3,4)

In [39]:
arr2d

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
x2 = torch.as_tensor(arr2d)

In [41]:
x2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [48]:
arr[0] = 121212

In [51]:
# the data from tensor was change as array
x

tensor([121212,      2,      3,      4,      5], dtype=torch.int32)

In [54]:
my_tensor = torch.tensor(arr2d)

In [55]:
my_tensor

tensor([[1.2121e+05, 1.2121e+05, 1.2121e+05, 1.2121e+05],
        [4.0000e+00, 5.0000e+00, 6.0000e+00, 7.0000e+00],
        [8.0000e+00, 9.0000e+00, 1.0000e+01, 1.1000e+01]], dtype=torch.float64)

In [57]:
arr2d[0][0] = 0

In [58]:
arr2d

array([[0.00000e+00, 1.21212e+05, 1.21212e+05, 1.21212e+05],
       [4.00000e+00, 5.00000e+00, 6.00000e+00, 7.00000e+00],
       [8.00000e+00, 9.00000e+00, 1.00000e+01, 1.10000e+01]])

In [60]:
# the torch.tensor() was not changed when the array was change due to torch.tensor() make a copy from array
my_tensor

tensor([[1.2121e+05, 1.2121e+05, 1.2121e+05, 1.2121e+05],
        [4.0000e+00, 5.0000e+00, 6.0000e+00, 7.0000e+00],
        [8.0000e+00, 9.0000e+00, 1.0000e+01, 1.1000e+01]], dtype=torch.float64)