<a href="https://colab.research.google.com/github/YasinRezvani/Python_Learning_Practice_Notebooks/blob/master/Exercise%20Notebooks/Playing%20with%20numpy%20library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
first_array = np.array([[10,20,30],[40,50,60]])

In [ ]:
print(first_array)

[[10 20 30]
 [40 50 60]]


In [ ]:
for i in first_array:
    print(i)

[10 20 30]
[40 50 60]


In [ ]:
for i in first_array:
    for j in i:
        print(j)

10
20
30
40
50
60


In [ ]:
type(first_array)

numpy.ndarray

In [ ]:
second_array = np.array(range(100))

In [ ]:
print(second_array.reshape(10,10))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
third_array = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

In [ ]:
for i in third_array:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


In [ ]:
for i in np.nditer(third_array):
    print(i)

0
1
2
3
4
5
6
7


In [ ]:
# hey, binary to decimal system, I'm lucky :)
for i,j in np.ndenumerate(third_array):
    print(i,j)

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


In [ ]:
python_list = [[1,2] , [3,4] , [5,6]]

In [ ]:
np.array(python_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(10 , int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((3,3) , int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones((5,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
#diagonal matrices
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
#between 0 and 1
np.random.rand(3,3)

array([[0.52647355, 0.47632649, 0.08134257],
       [0.36880024, 0.70807117, 0.52883203],
       [0.81149216, 0.96332086, 0.71166799]])

In [ ]:
# standard distribution contain variance number(negetive)
np.random.randn(2,4)

array([[ 0.78823706,  0.62388191,  0.01946724,  1.53333519],
       [ 0.05829164, -1.9194897 ,  0.72540658,  0.99360274]])

In [ ]:
np.random.randint(0,50,(3,5))

array([[14, 23, 14,  6, 12],
       [30, 20,  7,  1, 21],
       [48, 24, 15, 35, 45]])

In [ ]:
# but this section doesn't change any compile and default value with np.random.seed()
# especially in machine learning algorithms
np.random.seed(42)
np.random.randint(0,100,10)

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [ ]:
# in any compile reproduce new value
np.random.randint(0,100,10)

array([87, 99, 23,  2, 21, 52,  1, 87, 29, 37])

In [ ]:
ex_arr = np.random.randint(0,100,10)

In [ ]:
type(ex_arr)

numpy.ndarray

In [ ]:
ex_arr.dtype

dtype('int32')

In [ ]:
ex_arr.shape

(10,)

In [ ]:
ex_arr.reshape(2,5)

array([[ 1, 63, 59, 20, 32],
       [75, 57, 21, 88, 48]])

In [ ]:
ex_arr.max()

88

In [ ]:
ex_arr.argmax()

8

In [2]:
import matplotlib